name: build

on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:

   test:
     runs-on: ubuntu-18.04
     steps:
       - name: Git checkout
         uses: actions/checkout@v1
         with:
           fetch-depth: 1
           submodules: 'true'

       - name: Cache deps
         uses: actions/cache@v1
         id: cache-deps
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
           restore-keys: ${{ runner.os }}-maven-

       - name: Fetch deps
         if: steps.cache-deps.outputs.cache-hit != 'true'
         run: lein deps

       - name: Run tests
         run: script/test/jvm

   lint:
     runs-on: ubuntu-18.04
     steps:
       - name: Git checkout
         uses: actions/checkout@v1
         with:
           fetch-depth: 1
           submodules: 'true'

       - uses: DeLaGuardo/setup-clj-kondo@master
         with:
           version: '2020.05.09'

       - name: Lint
         run: script/lint

   style:
     runs-on: ubuntu-18.04
     steps:
       - name: Git checkout
         uses: actions/checkout@v1
         with:
           fetch-depth: 1
           submodules: 'true'

       - name: Style
         run: script/style

   carve:
     runs-on: ubuntu-18.04
     steps:
       - name: Git checkout
         uses: actions/checkout@v1
         with:
           fetch-depth: 1
           submodules: 'true'

       - uses: DeLaGuardo/setup-clojure@master
         with:
           tools-deps: '1.10.1.469'

       - name: Cache deps
         uses: actions/cache@v1
         id: cache-deps
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
           restore-keys: ${{ runner.os }}-maven-

       - name: Fetch deps
         if: steps.cache-deps.outputs.cache-hit != 'true'
         run: clojure -A:carve -Stree

       - name: Carve unused vars
         run: script/carve


